// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIDCOP_Backend.Entities.Entities;

public partial class tbAccionesPorPantalla
{
    public int AcPa_Id { get; set; }

    public int Pant_Id { get; set; }

    public int Acci_Id { get; set; }

    public virtual tbAcciones Acci { get; set; }

    public virtual tbPantallas Pant { get; set; }

    public virtual ICollection<tbPermisos> tbPermisos { get; set; } = new List<tbPermisos>();
}