// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIDCOP_Backend.Entities.Entities;

public partial class tbAcciones
{
    public int Acci_Id { get; set; }

    public string Acci_Descripcion { get; set; }

    public virtual ICollection<tbAccionesPorPantalla> tbAccionesPorPantalla { get; set; } = new List<tbAccionesPorPantalla>();
}