// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace SIDCOP_Backend.Entities.Entities;

public partial class tbAvales
{
    public int Aval_Id { get; set; }

    public int Clie_Id { get; set; }

    public string Aval_Nombres { get; set; }

    public string Aval_Apellidos { get; set; }

    public string Aval_ParentescoConCliente { get; set; }

    public string Aval_DNI { get; set; }

    public string Aval_Telefono { get; set; }

    public int TiVi_Id { get; set; }

    public string Aval_DireccionExacta { get; set; }

    public int Colo_Id { get; set; }

    public DateTime? Aval_FechaNacimiento { get; set; }

    public int? EsCv_Id { get; set; }

    [NotMapped]
    public string? Aval_Sexo { get; set; } 

    public int Usua_Creacion { get; set; }

    public DateTime Aval_FechaCreacion { get; set; }

    public int? Usua_Modificacion { get; set; }

    public DateTime? Aval_FechaModificacion { get; set; }

    public bool Aval_Estado { get; set; }

    public virtual tbClientes Clie { get; set; }

    public virtual tbColonias Colo { get; set; }

    public virtual tbEstadosCiviles EsCv { get; set; }

    public virtual tbTiposDeVivienda TiVi { get; set; }

    public virtual tbUsuarios Usua_CreacionNavigation { get; set; }

    public virtual tbUsuarios Usua_ModificacionNavigation { get; set; }
}