// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace SIDCOP_Backend.Entities.Entities;

public partial class tbBodegas
{
    public int Bode_Id { get; set; }

    public string Bode_Descripcion { get; set; }

    public int Sucu_Id { get; set; }

    public int RegC_Id { get; set; }

    public int Vend_Id { get; set; }

    public int Mode_Id { get; set; }

    public string Vehi_VIN { get; set; }

    public string Vehi_Placa { get; set; }

    public decimal Vehi_Capacidad { get; set; }

    public string Vehi_TipoCamion { get; set; }

    public int Usua_Creacion { get; set; }

    public DateTime Bode_FechaCreacion { get; set; }

    public int? Usua_Modificacion { get; set; }

    public DateTime? Bode_FechaModificacion { get; set; }

    [NotMapped]

    public string? Sucu_Descripcion { get; set; }

    public virtual tbModelos Mode { get; set; }

    public virtual tbRegistrosCAI RegC { get; set; }

    public virtual tbSucursales Sucu { get; set; }

    public virtual tbUsuarios Usua_CreacionNavigation { get; set; }

    public virtual tbUsuarios Usua_ModificacionNavigation { get; set; }

    public virtual tbVendedores Vend { get; set; }

    public virtual ICollection<tbInventarioBodegas> tbInventarioBodegas { get; set; } = new List<tbInventarioBodegas>();

    public virtual ICollection<tbRecargas> tbRecargas { get; set; } = new List<tbRecargas>();

    public virtual ICollection<tbTraslados> tbTraslados { get; set; } = new List<tbTraslados>();
}