// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace SIDCOP_Backend.Entities.Entities;

public partial class tbCanales
{
    public int Cana_Id { get; set; }

    public string Cana_Descripcion { get; set; }

    public string Cana_Observaciones { get; set; }

    public int Usua_Creacion { get; set; }

    public DateTime Cana_FechaCreacion { get; set; }

    public int? Usua_Modificacion { get; set; }

    public DateTime? Cana_FechaModificacion { get; set; }

    public bool Cana_Estado { get; set; }
    
    [NotMapped]
    public string UsuaC_Nombre { get; set; }

    [NotMapped]
    public string UsuaM_Nombre { get; set; }

    public virtual tbUsuarios Usua_CreacionNavigation { get; set; }

    public virtual tbUsuarios Usua_ModificacionNavigation { get; set; }

    public virtual ICollection<tbClientes> tbClientes { get; set; } = new List<tbClientes>();

    public virtual ICollection<tbDescuentos> tbDescuentos { get; set; } = new List<tbDescuentos>();
}