// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIDCOP_Backend.Entities.Entities;

public partial class tbCategorias
{
    public int Cate_Id { get; set; }

    public string Cate_Descripcion { get; set; }

    public int Usua_Creacion { get; set; }

    public DateTime Cate_FechaCreacion { get; set; }

    public int? Usua_Modificacion { get; set; }

    public DateTime? Cate_FechaModificacion { get; set; }

    public bool Cate_Estado { get; set; }

    public virtual tbUsuarios Usua_CreacionNavigation { get; set; }

    public virtual tbUsuarios Usua_ModificacionNavigation { get; set; }

    public virtual ICollection<tbSubcategorias> tbSubcategorias { get; set; } = new List<tbSubcategorias>();
}