// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace SIDCOP_Backend.Entities.Entities;

public partial class tbClientes
{
    public int Clie_Id { get; set; }

    public string Clie_Codigo { get; set; }

    public string Clie_Nacionalidad { get; set; }

    public string Clie_DNI { get; set; }

    public string Clie_RTN { get; set; }

    public string Clie_Nombres { get; set; }

    public string Clie_Apellidos { get; set; }

    public string Clie_NombreNegocio { get; set; }

    public string Clie_ImagenDelNegocio { get; set; }

    public string Clie_Telefono { get; set; }

    public string Clie_Correo { get; set; }

    public string Clie_Sexo { get; set; }

    public DateTime? Clie_FechaNacimiento { get; set; }

    public int? TiVi_Id { get; set; }

    public int Cana_Id { get; set; }

    public int? EsCv_Id { get; set; }

    public int? Ruta_Id { get; set; }

    public decimal? Clie_LimiteCredito { get; set; }

    public int? Clie_DiasCredito { get; set; }

    public decimal? Clie_Saldo { get; set; }

    public bool? Clie_Vencido { get; set; }

    public string Clie_Observaciones { get; set; }

    public string Clie_ObservacionRetiro { get; set; }

    public bool? Clie_Confirmacion { get; set; }

    public int Usua_Creacion { get; set; }

    public DateTime Clie_FechaCreacion { get; set; }

    public int? Usua_Modificacion { get; set; }

    public DateTime? Clie_FechaModificacion { get; set; }

    public bool Clie_Estado { get; set; }

    [NotMapped]
    public string? UsuaC_Nombre { get; set; }
    [NotMapped]

    public string? UsuaM_Nombre { get; set; }

    [NotMapped]
    public string? TiVi_Descripcion { get; set; }

    [NotMapped]

    public string? Cana_Descripcion { get; set; }
    [NotMapped]

    public string? Colo_Descripcion { get; set; }
    [NotMapped]

    public string? EsCv_Descripcion { get; set; }
    [NotMapped]

    public string? Ruta_Descripcion { get; set; }

    [NotMapped]
    public string? Pais_Descripcion { get; set; }

    [NotMapped]
    public int Secuencia { get; set; }

    public virtual tbCanales Cana { get; set; }

    public virtual tbPaises Clie_NacionalidadNavigation { get; set; }

    public virtual tbEstadosCiviles EsCv { get; set; }

    public virtual tbRutas Ruta { get; set; }

    public virtual tbTiposDeVivienda TiVi { get; set; }

    public virtual tbUsuarios Usua_CreacionNavigation { get; set; }

    public virtual tbUsuarios Usua_ModificacionNavigation { get; set; }

    public virtual ICollection<tbAvales> tbAvales { get; set; } = new List<tbAvales>();

    public virtual ICollection<tbCuentasPorCobrar> tbCuentasPorCobrar { get; set; } = new List<tbCuentasPorCobrar>();

    public virtual ICollection<tbDescuentoPorClientes> tbDescuentoPorClientes { get; set; } = new List<tbDescuentoPorClientes>();

    public virtual ICollection<tbDevoluciones> tbDevoluciones { get; set; } = new List<tbDevoluciones>();

    public virtual ICollection<tbDireccionesPorCliente> tbDireccionesPorCliente { get; set; } = new List<tbDireccionesPorCliente>();

    public virtual ICollection<tbFacturas> tbFacturas { get; set; } = new List<tbFacturas>();

    public virtual ICollection<tbPreciosPorProducto> tbPreciosPorProducto { get; set; } = new List<tbPreciosPorProducto>();

    public virtual ICollection<tbPromocionesPorClientes> tbPromocionesPorClientes { get; set; } = new List<tbPromocionesPorClientes>();
}