// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIDCOP_Backend.Entities.Entities;

public partial class tbClientes
{
    public int Clie_Id { get; set; }

    public string Clie_Codigo { get; set; }

    public string Clie_DNI { get; set; }

    public string Clie_RTN { get; set; }

    public string Clie_Nombres { get; set; }

    public string Clie_Apellidos { get; set; }

    public string Clie_NombreNegocio { get; set; }

    public string Clie_DireccionExacta { get; set; }

    public string Clie_Telefono { get; set; }

    public string Clie_Correo { get; set; }

    public string Clie_Sexo { get; set; }

    public DateOnly Clie_FechaNacimiento { get; set; }

    public int Cana_Id { get; set; }

    public int Colo_Id { get; set; }

    public int? EsCv_Id { get; set; }

    public decimal Clie_Latitud { get; set; }

    public decimal Clie_Longitud { get; set; }

    public int? Ruta_Id { get; set; }

    public decimal? Clie_LimiteCredito { get; set; }

    public int? Clie_DiasCredito { get; set; }

    public decimal? Clie_Saldo { get; set; }

    public bool? Clie_Vencido { get; set; }

    public string Clie_Observaciones { get; set; }

    public string Clie_ObservacionRetiro { get; set; }

    public int Usua_Creacion { get; set; }

    public DateTime Clie_FechaCreacion { get; set; }

    public int? Usua_Modificacion { get; set; }

    public DateTime? Clie_FechaModificacion { get; set; }

    public bool Clie_Estado { get; set; }

    public bool? Clie_Confirmacion { get; set; }

    public virtual tbCanales Cana { get; set; }

    public virtual tbColonias Colo { get; set; }

    public virtual tbEstadosCiviles EsCv { get; set; }

    public virtual tbRutas Ruta { get; set; }

    public virtual tbUsuarios Usua_CreacionNavigation { get; set; }

    public virtual tbUsuarios Usua_ModificacionNavigation { get; set; }

    public virtual ICollection<tbCuentasPorCobrar> tbCuentasPorCobrar { get; set; } = new List<tbCuentasPorCobrar>();

    public virtual ICollection<tbFacturas> tbFacturas { get; set; } = new List<tbFacturas>();

    public virtual ICollection<tbPedidos> tbPedidos { get; set; } = new List<tbPedidos>();
}