// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace SIDCOP_Backend.Entities.Entities;

public partial class tbClientesVisita
{
    public int ClVi_Id { get; set; }

    public int? VeRu_Id { get; set; }

    [NotMapped]
    public int? Vend_Id { get; set; }

    [NotMapped]
    public string? Vendedor { get; set; }

    [NotMapped]
    public string? Cliente { get; set; }

    [NotMapped]
    public string? Clie_NombreNegocio { get; set; }

    [NotMapped]
    public string? EsVi_Descripcion { get; set; }

    public string ClVi_Observaciones { get; set; }

    public DateTime? ClVi_Fecha { get; set; }

    public int? Usua_Creacion { get; set; }

    [NotMapped]
    public string? UsuarioCreacion { get; set; }

    public DateTime? ClVi_FechaCreacion { get; set; }

    public int? DiCl_Id { get; set; }

    public int? EsVi_Id { get; set; }

    public decimal? ClVi_Latitud { get; set; }

    public decimal? ClVi_Longitud { get; set; }


    public virtual tbDireccionesPorCliente DiCl { get; set; }

    public virtual tbEstadosVisita EsVi { get; set; }

    public virtual tbUsuarios Usua_CreacionNavigation { get; set; }

    public virtual tbVendedoresPorRuta VeRu { get; set; }

    public virtual ICollection<tbImagenesVisita> tbImagenesVisita { get; set; } = new List<tbImagenesVisita>();
}