// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIDCOP_Backend.Entities.Entities;

public partial class tbClientesVisitaHistorial
{
    public int HCVi_Id { get; set; }

    public int? VeRu_Id { get; set; }

    public int? Clie_Id { get; set; }

    public string HCVi_Foto { get; set; }

    public string HCVi_Observaciones { get; set; }

    public DateTime? HCVi_Fecha { get; set; }

    public decimal? HCVi_Latitud { get; set; }

    public decimal? HCVi_Longitud { get; set; }

    public int Usua_Creacion { get; set; }

    public DateTime HCVi_FechaCreacion { get; set; }

} 