// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace SIDCOP_Backend.Entities.Entities;

public partial class tbConfiguracionFacturas
{
    public int CoFa_Id { get; set; }

    public string CoFa_NombreEmpresa { get; set; }

    public string CoFa_DireccionEmpresa { get; set; }

    public string CoFa_RTN { get; set; }

    public string CoFa_Correo { get; set; }

    public string CoFa_Telefono1 { get; set; }

    public string CoFa_Telefono2 { get; set; }

    public string CoFa_Logo { get; set; }

    public int Colo_Id { get; set; }

    public int Usua_Creacion { get; set; }

    public DateTime CoFa_FechaCreacion { get; set; }

    public int? Usua_Modificacion { get; set; }

    public DateTime? CoFa_FechaModificacion { get; set; }

    public virtual tbColonias Colo { get; set; }

    public virtual tbUsuarios Usua_CreacionNavigation { get; set; }

    public virtual tbUsuarios Usua_ModificacionNavigation { get; set; }


    [NotMapped]
    public string? Colo_Descripcion { get; set; }

    [NotMapped]
    public string? Muni_Codigo { get; set; }

    [NotMapped]
    public string? Muni_Descripcion { get; set; }

    [NotMapped]
    public string? Depa_Codigo { get; set; }
    [NotMapped]
    public string? Depa_Descripcion { get; set; }
    [NotMapped]
    public string? UsuarioCreacion { get; set; }
    [NotMapped]
    public string? UsuarioModificacion { get; set; }

}