// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIDCOP_Backend.Entities.Entities;

public partial class tbControlMigraciones
{
    public string CoMi_Tabla { get; set; }

    public DateTime? CoMi_UltimaFechaMigracion { get; set; }
}