// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace SIDCOP_Backend.Entities.Entities;

public partial class tbColonias
{
    public int Colo_Id { get; set; }

    public string Colo_Descripcion { get; set; }

    public string Muni_Codigo { get; set; }

    public int Usua_Creacion { get; set; }

    public DateTime Colo_FechaCreacion { get; set; }

    public int? Usua_Modificacion { get; set; }

    [NotMapped]
    public int? Secuencia { get; set; }

    [NotMapped]
    public string? Muni_Descripcion { get; set; }

    [NotMapped]
    public string Depa_Codigo { get; set; }

    [NotMapped]
    public string? Depa_Descripcion { get; set; }

    [NotMapped]
    public string? UsuarioCreacion { get; set; }

    [NotMapped]
    public string? UsuarioModificacion { get; set; }

    public DateTime? Colo_FechaModificacion { get; set; }

    public virtual tbMunicipios Muni_CodigoNavigation { get; set; }

    public virtual tbUsuarios Usua_CreacionNavigation { get; set; }

    public virtual tbUsuarios Usua_ModificacionNavigation { get; set; }

    public virtual ICollection<tbConfiguracionFacturas> tbConfiguracionFacturas { get; set; } = new List<tbConfiguracionFacturas>();

    public virtual ICollection<tbDireccionesPorCliente> tbDireccionesPorCliente { get; set; } = new List<tbDireccionesPorCliente>();

    public virtual ICollection<tbEmpleados> tbEmpleados { get; set; } = new List<tbEmpleados>();

    public virtual ICollection<tbProveedores> tbProveedores { get; set; } = new List<tbProveedores>();

    public virtual ICollection<tbSucursales> tbSucursales { get; set; } = new List<tbSucursales>();

    public virtual ICollection<tbVendedores> tbVendedores { get; set; } = new List<tbVendedores>();
}