// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIDCOP_Backend.Entities.Entities;

public partial class tbCuentasPorCobrar
{
    public int CPCo_Id { get; set; }

    public int Clie_Id { get; set; }

    public int Fact_Id { get; set; }

    public DateOnly CPCo_FechaEmision { get; set; }

    public DateOnly? CPCo_FechaVencimiento { get; set; }

    public decimal CPCo_Valor { get; set; }

    public decimal CPCo_Saldo { get; set; }

    public string CPCo_Observaciones { get; set; }

    public bool? CPCo_Anulado { get; set; }

    public bool? CPCo_Saldada { get; set; }

    public int Usua_Creacion { get; set; }

    public DateTime CPCo_FechaCreacion { get; set; }

    public int? Usua_Modificacion { get; set; }

    public DateTime? CPCo_FechaModificacion { get; set; }

    public bool CPCo_Estado { get; set; }

    public virtual tbClientes Clie { get; set; }

    public virtual tbFacturas Fact { get; set; }

    public virtual tbUsuarios Usua_CreacionNavigation { get; set; }

    public virtual tbUsuarios Usua_ModificacionNavigation { get; set; }

    public virtual ICollection<tbPagosCuentasPorCobrar> tbPagosCuentasPorCobrar { get; set; } = new List<tbPagosCuentasPorCobrar>();
}