// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace SIDCOP_Backend.Entities.Entities;

public partial class tbCuentasPorCobrar
{
    public int CPCo_Id { get; set; }

    public int Clie_Id { get; set; }

    public int Fact_Id { get; set; }

    public DateTime CPCo_FechaEmision { get; set; }

    public DateTime? CPCo_FechaVencimiento { get; set; }

    public decimal CPCo_Valor { get; set; }

    public decimal CPCo_Saldo { get; set; }

    public string CPCo_Observaciones { get; set; }

    public bool? CPCo_Anulado { get; set; }

    public bool? CPCo_Saldada { get; set; }


    public int Usua_Creacion { get; set; }

    public DateTime CPCo_FechaCreacion { get; set; }

    public int? Usua_Modificacion { get; set; }

    public DateTime? CPCo_FechaModificacion { get; set; }

    public bool CPCo_Estado { get; set; }

    [NotMapped] public string Clie_Codigo { get; set; }
    [NotMapped] public string Clie_Nombres { get; set; }
    [NotMapped] public string Clie_Apellidos { get; set; }
    [NotMapped] public string Cliente { get; set; }
    [NotMapped] public string Clie_NombreNegocio { get; set; }
    [NotMapped] public string Clie_Telefono { get; set; }
    [NotMapped] public string FormaPago { get; set; }
    [NotMapped] public decimal Clie_LimiteCredito { get; set; }
    [NotMapped] public decimal Clie_Saldo { get; set; }
    [NotMapped] public bool? EstaVencida { get; set; }
    [NotMapped] public string Tipo { get; set; }
    [NotMapped] public string Referencia { get; set; }
    [NotMapped] public decimal Monto { get; set; }
    [NotMapped] public DateTime Fecha { get; set; }

    [NotMapped] public decimal Actual { get; set; }
    [NotMapped] public decimal _1_30 { get; set; }
    [NotMapped] public decimal _31_60 { get; set; }
    [NotMapped] public decimal _61_90 { get; set; }
    [NotMapped] public decimal Mayor90 { get; set; }

    [NotMapped] public int FacturasPendientes { get; set; }
    [NotMapped] public decimal TotalFacturado { get; set; }
    [NotMapped] public decimal Total { get; set; }
    [NotMapped] public decimal TotalPendiente { get; set; }
    [NotMapped] public decimal TotalVencido { get; set; }
    [NotMapped] public DateTime UltimoPago { get; set; }

    [NotMapped] public string UsuarioCreacion { get; set; }
    [NotMapped] public string UsuarioModificacion { get; set; }
    [NotMapped] public string Secuencia { get; set; }

    public virtual tbClientes Clie { get; set; }

    public virtual tbFacturas Fact { get; set; }

    public virtual tbUsuarios Usua_CreacionNavigation { get; set; }

    public virtual tbUsuarios Usua_ModificacionNavigation { get; set; }

    public virtual ICollection<tbPagosCuentasPorCobrar> tbPagosCuentasPorCobrar { get; set; } = new List<tbPagosCuentasPorCobrar>();
}