// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIDCOP_Backend.Entities.Entities;

public partial class tbDescuentosHistorial
{
    public int HiDe_Id { get; set; }

    public int? Desc_Id { get; set; }

    public string Desc_Descripcion { get; set; }

    public bool? Desc_Tipo { get; set; }

    public string Desc_Aplicar { get; set; }

    public DateTime? Desc_FechaInicio { get; set; }

    public DateTime? Desc_FechaFin { get; set; }

    public string Desc_Observaciones { get; set; }

    public string Desc_TipoFactura { get; set; }

    public bool? Desc_Estado { get; set; }

    public string HiDe_Accion { get; set; }

    public DateTime HiDe_FechaAccion { get; set; }

    public int HiDe_UsuarioAccion { get; set; }
}