// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIDCOP_Backend.Entities.Entities;

public partial class tbDescuentosPorEscalaHistorial
{
    public int HDEs_Id { get; set; }

    public int? DeEs_Id { get; set; }

    public int? Desc_Id { get; set; }

    public int? DeEs_InicioEscala { get; set; }

    public int? DeEs_FinEscala { get; set; }

    public decimal? DeEs_Valor { get; set; }

    public bool? DeEs_Estado { get; set; }

    public string HDEs_Accion { get; set; }

    public DateTime HDEs_FechaAccion { get; set; }

    public int HDEs_UsuarioAccion { get; set; }
}