// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIDCOP_Backend.Entities.Entities;

public partial class tbDevolucionesHistorial
{
    public int HDev_Id { get; set; }

    public int? Devo_Id { get; set; }

    public int? Clie_Id { get; set; }

    public int? Fact_Id { get; set; }

    public DateTime? Devo_Fecha { get; set; }

    public string Devo_Motivo { get; set; }

    public bool? Devo_Estado { get; set; }

    public string HDev_Accion { get; set; }

    public DateTime HDev_FechaAccion { get; set; }

    public int HDev_UsuarioAccion { get; set; }
}