// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIDCOP_Backend.Entities.Entities;

public partial class tbDescuentoPorClientesHistorial
{
    public int HDeC_Id { get; set; }

    public int? DeCl_Id { get; set; }

    public int? Desc_Id { get; set; }

    public int? Clie_Id { get; set; }

    public bool? DeCl_Estado { get; set; }

    public string HDeC_Accion { get; set; }

    public DateTime HDeC_FechaAccion { get; set; }

    public int HDeC_UsuarioAccion { get; set; }
}