// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace SIDCOP_Backend.Entities.Entities;

public partial class tbDescuentos
{
    public int Desc_Id { get; set; }

    public string Desc_Descripcion { get; set; }

    public bool Desc_Tipo { get; set; }

    public string Desc_Aplicar { get; set; }

    public DateTime Desc_FechaInicio { get; set; }

    public DateTime Desc_FechaFin { get; set; }

    public string Desc_Observaciones { get; set; }

    public int Usua_Creacion { get; set; }

    public DateTime Desc_FechaCreacion { get; set; }

    public int? Usua_Modificacion { get; set; }

    public DateTime? Desc_FechaModificacion { get; set; }

    public bool Desc_Estado { get; set; }

    [NotMapped]
    public string? clientes {  get; set; }

    [NotMapped]
    public string? referencias { get; set; }

    [NotMapped]
    public string? escalas { get; set; }

    [NotMapped]
    public List<int>? IdClientes { get; set; }

    [NotMapped]

    public List<int>? IdReferencias { get; set; }

    public virtual tbUsuarios Usua_CreacionNavigation { get; set; }

    public virtual tbUsuarios Usua_ModificacionNavigation { get; set; }

    public virtual ICollection<tbDescuentoPorClientes> tbDescuentoPorClientes { get; set; } = new List<tbDescuentoPorClientes>();

    public virtual ICollection<tbDescuentosDetalle> tbDescuentosDetalle { get; set; } = new List<tbDescuentosDetalle>();

    public virtual ICollection<tbDescuentosPorEscala> tbDescuentosPorEscala { get; set; } = new List<tbDescuentosPorEscala>();
}