// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIDCOP_Backend.Entities.Entities;

public partial class tbDescuentosDetalleHistorial
{
    public int HDeD_Id { get; set; }

    public int? DesD_Id { get; set; }

    public int? Desc_Id { get; set; }

    public int? DesD_IdReferencia { get; set; }

    public bool? DesD_Estado { get; set; }

    public string HDeD_Accion { get; set; }

    public DateTime HDeD_FechaAccion { get; set; }

    public int HDeD_UsuarioAccion { get; set; }
}