// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIDCOP_Backend.Entities.Entities;

public partial class tbDescuentosDetalle
{
    public int DesD_Id { get; set; }

    public int Desc_Id { get; set; }

    public int DesD_IdReferencia { get; set; }

    public int Usua_Creacion { get; set; }

    public DateTime DesD_FechaCreacion { get; set; }

    public int? Usua_Modificacion { get; set; }

    public DateTime? DesD_FechaModificacion { get; set; }

    public bool DesD_Estado { get; set; }

    public virtual tbDescuentos Desc { get; set; }

    public virtual tbUsuarios Usua_CreacionNavigation { get; set; }

    public virtual tbUsuarios Usua_ModificacionNavigation { get; set; }
}