// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIDCOP_Backend.Entities.Entities;

public partial class tbDevolucionesDetalleHistorial
{
    public int HDDe_Id { get; set; }

    public int? DevD_Id { get; set; }

    public int? Devo_Id { get; set; }

    public int? Prod_Id { get; set; }

    public bool? DevD_Estado { get; set; }

    public string HDDe_Accion { get; set; }

    public DateTime HDDe_FechaAccion { get; set; }

    public int HDDe_UsuarioAccion { get; set; }
}