// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace SIDCOP_Backend.Entities.Entities;

public partial class tbDevolucionesDetalle
{
    public int DevD_Id { get; set; }

    public int Devo_Id { get; set; }

    public int Prod_Id { get; set; }

    public int Usua_Creacion { get; set; }

    public DateTime DevD_FechaCreacion { get; set; }

    public int? Usua_Modificacion { get; set; }

    public DateTime? DevD_FechaModificacion { get; set; }

    public bool DevD_Estado { get; set; }

    public int DevD_Cantidad { get; set; }

    [NotMapped]
    public int? Secuencia { get; set; }

    [NotMapped]
    public string? Cate_Descripcion { get; set; }

    [NotMapped]
    public string? Prod_Imagen { get; set; }

    [NotMapped]
    public string? Prod_Descripcion { get; set; }
    [NotMapped]
    public string? Productos_Devueltos { get; set; }
    [NotMapped]
    public string? Prod_DescripcionCorta { get; set; }

    [NotMapped]
    public string? UsuarioCreacion { get; set; }

    [NotMapped]
    public string? UsuarioModificacion { get; set; }


    public int? DevD_Cantidad { get; set; }

    public virtual tbDevoluciones Devo { get; set; }

    public virtual tbProductos Prod { get; set; }

    public virtual tbUsuarios Usua_CreacionNavigation { get; set; }

    public virtual tbUsuarios Usua_ModificacionNavigation { get; set; }
}