// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace SIDCOP_Backend.Entities.Entities;

public partial class tbDevoluciones
{
    public int Devo_Id { get; set; }

    public int? Fact_Id { get; set; }

    public DateTime Devo_Fecha { get; set; }

    public string Devo_Motivo { get; set; }

    public int Usua_Creacion { get; set; }

    public DateTime Devo_FechaCreacion { get; set; }

    public int? Usua_Modificacion { get; set; }

    public DateTime? Devo_FechaModificacion { get; set; }

    public bool Devo_Estado { get; set; }

    public bool Devo_EnSucursal { get; set; }

    [NotMapped]
    public string Nombre_Completo { get; set; }

    [NotMapped]
    public string Clie_NombreNegocio { get; set; }

    [NotMapped]
    public string Fact_Numero { get; set; }

    [NotMapped]
    public string UsuarioCreacion { get; set; }

    [NotMapped]
    public string UsuarioModificacion { get; set; }

    [NotMapped]
    public string devoDetalle_XML { get; set; }

    public virtual tbFacturas Fact { get; set; }

    public virtual tbUsuarios Usua_CreacionNavigation { get; set; }

    public virtual tbUsuarios Usua_ModificacionNavigation { get; set; }

    public virtual ICollection<tbDevolucionesDetalle> tbDevolucionesDetalle { get; set; } = new List<tbDevolucionesDetalle>();
}