// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace SIDCOP_Backend.Entities.Entities;

public partial class tbDescuentosPorEscala
{
    public int DeEs_Id { get; set; }

    public int Desc_Id { get; set; }

    public int DeEs_InicioEscala { get; set; }

    public int DeEs_FinEscala { get; set; }

    public decimal DeEs_Valor { get; set; }

    public int Usua_Creacion { get; set; }

    public DateTime DeEs_FechaCreacion { get; set; }

    public int? Usua_Modificacion { get; set; }

    public DateTime? DeEs_FechaModificacion { get; set; }

    public bool DeEs_Estado { get; set; }

    [NotMapped]
    public string? Escala_JSON { get; set; }

    public virtual tbDescuentos Desc { get; set; }

    public virtual tbUsuarios Usua_CreacionNavigation { get; set; }

    public virtual tbUsuarios Usua_ModificacionNavigation { get; set; }
}