// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace SIDCOP_Backend.Entities.Entities;

public partial class tbDireccionesPorCliente
{
    public int DiCl_Id { get; set; }

    public int Clie_Id { get; set; }

    public int Colo_Id { get; set; }

    public string DiCl_DireccionExacta { get; set; }

    public string DiCl_Observaciones { get; set; }

    public decimal? DiCl_Latitud { get; set; }

    public decimal? DiCl_Longitud { get; set; }

    public int Usua_Creacion { get; set; }

    public DateTime DiCl_FechaCreacion { get; set; }

    public int? Usua_Modificacion { get; set; }

    public DateTime? DiCl_FechaModificacion { get; set; }

    [NotMapped]
    public string Colo_Descripcion { get; set; }

    [NotMapped]
    public string Muni_Descripcion { get; set; }

    [NotMapped]
    public string Depa_Descripcion { get; set; }

    [NotMapped]
    public string Clie_Codigo { get; set; }

    [NotMapped]
    public string Clie_Nombres { get; set; }

    [NotMapped]
    public string Clie_Apellidos { get; set; }

    public virtual tbClientes Clie { get; set; }

    public virtual tbColonias Colo { get; set; }

    public virtual tbUsuarios Usua_CreacionNavigation { get; set; }

    public virtual tbUsuarios Usua_ModificacionNavigation { get; set; }

    public virtual ICollection<tbClientesVisita> tbClientesVisita { get; set; } = new List<tbClientesVisita>();

    public virtual ICollection<tbPedidos> tbPedidos { get; set; } = new List<tbPedidos>();
}