// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace SIDCOP_Backend.Entities.Entities;

public partial class tbEmpleados
{
    public int Empl_Id { get; set; }

    public string Empl_DNI { get; set; }

    public string Empl_Codigo { get; set; }

    public string Empl_Nombres { get; set; }

    public string Empl_Apellidos { get; set; }

    [NotMapped]
    public string NombreCompleto { get; set; }

    public string Empl_Sexo { get; set; }

    public DateTime Empl_FechaNacimiento { get; set; }

    public string Empl_Correo { get; set; }

    public string Empl_Telefono { get; set; }

    public int Sucu_Id { get; set; }

    public int EsCv_Id { get; set; }

    public int Carg_Id { get; set; }

    public int Colo_Id { get; set; }
    [NotMapped]
    public string? Sucu_Descripcion { get; set; }

    [NotMapped]
    public string? EsCv_Descripcion { get; set; }

    [NotMapped]
    public string? Carg_Descripcion { get; set; }

    [NotMapped]
    public string? Colo_Descripcion { get; set; }

    [NotMapped]
    public string? UsuarioCreacion { get; set; }

    [NotMapped]
    public string? UsuarioModificacion { get; set; }

    [NotMapped]
    public string? Usua_Imagen { get; set; }


    public string Empl_DireccionExacta { get; set; }

    public int Usua_Creacion { get; set; }

    public DateTime Empl_FechaCreacion { get; set; }

    public int? Usua_Modificacion { get; set; }

    public DateTime? Empl_FechaModificacion { get; set; }

    public bool Empl_Estado { get; set; }

    public string Empl_Imagen { get; set; }

    public virtual tbCargos Carg { get; set; }

    public virtual tbColonias Colo { get; set; }

    public virtual tbEstadosCiviles EsCv { get; set; }

    public virtual tbSucursales Sucu { get; set; }

    public virtual tbUsuarios Usua_CreacionNavigation { get; set; }

    public virtual tbUsuarios Usua_ModificacionNavigation { get; set; }

    public virtual ICollection<tbPedidos> tbPedidos { get; set; } = new List<tbPedidos>();

    public virtual ICollection<tbRecargas> tbRecargas { get; set; } = new List<tbRecargas>();

    public virtual ICollection<tbVendedores> tbVendedoresVend_AyudanteNavigation { get; set; } = new List<tbVendedores>();

    public virtual ICollection<tbVendedores> tbVendedoresVend_SupervisorNavigation { get; set; } = new List<tbVendedores>();
}