// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIDCOP_Backend.Entities.Entities;

public partial class tbEstadosCiviles
{
    public int EsCv_Id { get; set; }

    public string EsCv_Descripcion { get; set; }

    public int Usua_Creacion { get; set; }

    public DateTime EsCv_FechaCreacion { get; set; }

    public int? Usua_Modificacion { get; set; }

    public DateTime? EsCv_FechaModificacion { get; set; }

    public virtual tbUsuarios Usua_CreacionNavigation { get; set; }

    public virtual tbUsuarios Usua_ModificacionNavigation { get; set; }

    public virtual ICollection<tbClientes> tbClientes { get; set; } = new List<tbClientes>();

    public virtual ICollection<tbEmpleados> tbEmpleados { get; set; } = new List<tbEmpleados>();
}