// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace SIDCOP_Backend.Entities.Entities;

public partial class tbEstadosVisita
{
    public int EsVi_Id { get; set; }

    public string EsVi_Descripcion { get; set; }

    public int? Usua_Creacion { get; set; }

    public DateTime? EsVi_FechaCreacion { get; set; }

    public int? Usua_Modificacion { get; set; }

    public DateTime? EsVi_FechaModificacion { get; set; }

    public virtual tbUsuarios Usua_CreacionNavigation { get; set; }

    public virtual tbUsuarios Usua_ModificacionNavigation { get; set; }

    public virtual ICollection<tbClientesVisita> tbClientesVisita { get; set; } = new List<tbClientesVisita>();

    [NotMapped]
    public int? Secuencia { get; set; }

    [NotMapped]
    public string UsuarioCreacion { get; set; }

    [NotMapped]
    public string UsuarioModificacion { get; set; }
}