// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIDCOP_Backend.Entities.Entities;

public partial class tbFacturasHistorial
{
    public int HFac_Id { get; set; }

    public int? Fact_Id { get; set; }

    public string Fact_Numero { get; set; }

    public string Fact_TipoDeDocumento { get; set; }

    public int? RegC_Id { get; set; }

    public int? Clie_Id { get; set; }

    public int? Vend_Id { get; set; }

    public string Fact_TipoVenta { get; set; }

    public DateTime? Fact_FechaEmision { get; set; }

    public DateTime? Fact_FechaLimiteEmision { get; set; }

    public string Fact_RangoInicialAutorizado { get; set; }

    public string Fact_RangoFinalAutorizado { get; set; }

    public decimal? Fact_TotalImpuesto15 { get; set; }

    public decimal? Fact_TotalImpuesto18 { get; set; }

    public decimal? Fact_ImporteExento { get; set; }

    public decimal? Fact_ImporteGravado15 { get; set; }

    public decimal? Fact_ImporteGravado18 { get; set; }

    public decimal? Fact_ImporteExonerado { get; set; }

    public decimal? Fact_TotalDescuento { get; set; }

    public decimal? Fact_Subtotal { get; set; }

    public decimal? Fact_Total { get; set; }

    public decimal? Fact_Latitud { get; set; }

    public decimal? Fact_Longitud { get; set; }

    public string Fact_Referencia { get; set; }

    public string Fact_AutorizadoPor { get; set; }

    public bool? Fact_Anulado { get; set; }

    public string Fact_Usuario { get; set; }

    public bool? Fact_Estado { get; set; }

    public string HFac_Accion { get; set; }

    public DateTime HFac_FechaAccion { get; set; }

    public int HFac_UsuarioAccion { get; set; }
}