// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIDCOP_Backend.Entities.Entities;

public partial class tbFacturasDetalleHistorial
{
    public int HFaD_Id { get; set; }

    public int? FaDe_Id { get; set; }

    public int? Fact_Id { get; set; }

    public int? Prod_Id { get; set; }

    public int? FaDe_Cantidad { get; set; }

    public decimal? FaDe_PrecioUnitario { get; set; }

    public decimal? FaDe_Impuesto { get; set; }

    public decimal? FaDe_Descuento { get; set; }

    public decimal? FaDe_Subtotal { get; set; }

    public decimal? FaDe_Total { get; set; }

    public bool? FaDe_Estado { get; set; }

    public string HFaD_Accion { get; set; }

    public DateTime HFaD_FechaAccion { get; set; }

    public int HFaD_UsuarioAccion { get; set; }
}