// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace SIDCOP_Backend.Entities.Entities;

public partial class tbImagenesVisita
{
    [NotMapped]
    public int? Secuencia { get; set; }

    public int ImVi_Id { get; set; }

    public string ImVi_Imagen { get; set; }

    public int ClVi_Id { get; set; }

    public int Usua_Creacion { get; set; }

    [NotMapped]
    public string? UsuarioCreacion { get; set; }

    public DateTime ImVi_FechaCreacion { get; set; }

    public virtual tbClientesVisita ClVi { get; set; }

    public virtual tbUsuarios Usua_CreacionNavigation { get; set; }
}