// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace SIDCOP_Backend.Entities.Entities;

public partial class tbImpuestos
{
    public int Impu_Id { get; set; }

    public string Impu_Descripcion { get; set; }

    public decimal Impu_Valor { get; set; }

    public int Usua_Creacion { get; set; }

    public DateTime Impu_FechaCreacion { get; set; }

    public int? Usua_Modificacion { get; set; }

    public DateTime? Impu_FechaModificacion { get; set; }

    public bool Impu_Estado { get; set; }

    [NotMapped]

    public int? Secuencia { get; set; }

    public virtual tbUsuarios Usua_CreacionNavigation { get; set; }

    public virtual tbUsuarios Usua_ModificacionNavigation { get; set; }

    public virtual ICollection<tbProductos> tbProductos { get; set; } = new List<tbProductos>();
}