// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIDCOP_Backend.Entities.Entities;

public partial class tbInventarioBodegasHistorial
{
    public int HIBo_Id { get; set; }

    public int? InBo_Id { get; set; }

    public int? Bode_Id { get; set; }

    public int? Prod_Id { get; set; }

    public int? InBo_Cantidad { get; set; }

    public bool? InBo_Estado { get; set; }

    public string HIBo_Accion { get; set; }

    public DateTime HIBo_FechaAccion { get; set; }

    public int HIBo_UsuarioAccion { get; set; }
}