// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIDCOP_Backend.Entities.Entities;

public partial class tbInventarioSucursalesHistorial
{
    public int HISu_Id { get; set; }

    public int? InSu_Id { get; set; }

    public int? Sucu_Id { get; set; }

    public int? Prod_Id { get; set; }

    public int? InSu_Cantidad { get; set; }

    public bool? InSu_Estado { get; set; }

    public string HISu_Accion { get; set; }

    public DateTime HISu_FechaAccion { get; set; }

    public int HISu_UsuarioAccion { get; set; }
}