// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIDCOP_Backend.Entities.Entities;

public partial class tbInventarioJornada
{
    public int InJo_Id { get; set; }

    public int JorV_Id { get; set; }

    public int Bode_Id { get; set; }

    public int Prod_Id { get; set; }

    public int InJo_CantidadInicial { get; set; }

    public DateTime InJo_FechaCreacion { get; set; }
}