// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace SIDCOP_Backend.Entities.Entities;

public partial class tbInventarioSucursales
{
    public int InSu_Id { get; set; }

    public int Sucu_Id { get; set; }

    [NotMapped]
    public string? Sucu_Descripcion { get; set; }

    public int Prod_Id { get; set; }

    [NotMapped]
    public string? Prod_Descripcion { get; set; }

    [NotMapped]
    public string? Prod_DescripcionCorta { get; set; }

    public int InSu_Cantidad { get; set; }

    [NotMapped]
    public string? Cambio { get; set; }

    public int Usua_Creacion { get; set; }

    public DateTime InSu_FechaCreacion { get; set; }

    public int? Usua_Modificacion { get; set; }

    public DateTime? InSu_FechaModificacion { get; set; }

    public bool InSu_Estado { get; set; }

    public virtual tbProductos Prod { get; set; }

    public virtual tbSucursales Sucu { get; set; }

    public virtual tbUsuarios Usua_CreacionNavigation { get; set; }

    public virtual tbUsuarios Usua_ModificacionNavigation { get; set; }
}