// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace SIDCOP_Backend.Entities.Entities;

public partial class tbInventarioBodegas
{
    public int InBo_Id { get; set; }

    public int Bode_Id { get; set; }

    public int Prod_Id { get; set; }

    public int InBo_Cantidad { get; set; }

    public int Usua_Creacion { get; set; }

    public DateTime InBo_FechaCreacion { get; set; }

    public int? Usua_Modificacion { get; set; }

    public DateTime? InBo_FechaModificacion { get; set; }

    public bool InBo_Estado { get; set; }

    [NotMapped]
    public int? CantidadAsignada { get; set; }
    [NotMapped]
    public double? Precio { get; set; }
    [NotMapped]
    public string? CodigoProducto { get; set; }
    [NotMapped]
    public string? Subc_Descripcion { get; set; }
    [NotMapped]
    public string? Prod_Imagen { get; set; }
    [NotMapped]
    public string? NombreProducto { get; set; }
    [NotMapped]
    public string? CantidadActual { get; set; }

    public virtual tbBodegas Bode { get; set; }

    public virtual tbProductos Prod { get; set; }

    public virtual tbUsuarios Usua_CreacionNavigation { get; set; }

    public virtual tbUsuarios Usua_ModificacionNavigation { get; set; }
}


// DTO del encabezado
public class ReporteJornadaHeaderDto
{
    public string RutaDescripcion { get; set; } = string.Empty;
    public string Vendedor { get; set; } = string.Empty;
}

// DTO del detalle de productos
public class ReporteJornadaDetalleDto
{
    public string Producto { get; set; } = string.Empty;
    public string Codigo { get; set; } = string.Empty;
    public int Inicial { get; set; }
    public int Final { get; set; }
    public int Vendido { get; set; }
    public decimal SubTotal { get; set; }
}

// DTO del reporte completo (header + lista de detalle)
public class ReporteJornadaDto
{
    public ReporteJornadaHeaderDto Header { get; set; } = new ReporteJornadaHeaderDto();
    public List<ReporteJornadaDetalleDto> Detalle { get; set; } = new List<ReporteJornadaDetalleDto>();
}