// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIDCOP_Backend.Entities.Entities;

public partial class tbJornadasVendedor
{
    public int JorV_Id { get; set; }

    public int Vend_Id { get; set; }

    public DateOnly JorV_Fecha { get; set; }

    public DateTime? JorV_HoraInicio { get; set; }

    public DateTime? JorV_HoraFin { get; set; }

    public string JorV_Estado { get; set; }

    public int Usua_Creacion { get; set; }

    public DateTime JorV_FechaCreacion { get; set; }
}