// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace SIDCOP_Backend.Entities.Entities;

public partial class tbMarcasVehiculos
{
    public int MaVe_Id { get; set; }

    public string MaVe_Marca { get; set; }

    public int Usua_Creacion { get; set; }

    public DateTime MaVe_FechaCreacion { get; set; }

    public int? Usua_Modificacion { get; set; }

    public DateTime? MaVe_FechaModificacion { get; set; }

    public bool MaVe_Estado { get; set; }
    [NotMapped]
    public string UsuarioCreacion { get; set; }

    [NotMapped]
    public string UsuarioModificacion { get; set; }


    public virtual tbUsuarios Usua_CreacionNavigation { get; set; }

    public virtual tbUsuarios Usua_ModificacionNavigation { get; set; }

    public virtual ICollection<tbModelos> tbModelos { get; set; } = new List<tbModelos>();
}