// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIDCOP_Backend.Entities.Entities;

public partial class tbMetas
{
    public int Meta_Id { get; set; }

    public string Meta_Descripcion { get; set; }

    public DateTime Meta_FechaInicio { get; set; }

    public DateTime Meta_FechaFin { get; set; }

    public string Meta_Tipo { get; set; }

    public decimal? Meta_Ingresos { get; set; }

    public int? Meta_Unidades { get; set; }

    public int? Prod_Id { get; set; }

    public int? Cate_Id { get; set; }

    public bool Meta_Estado { get; set; }

    public int Usua_Creacion { get; set; }

    public DateTime Meta_FechaCreacion { get; set; }

    public int? Usua_Modificacion { get; set; }

    public DateTime? Meta_FechaModificacion { get; set; }

    public virtual tbCategorias Cate { get; set; }

    public virtual tbProductos Prod { get; set; }

    public virtual tbUsuarios Usua_CreacionNavigation { get; set; }

    public virtual tbUsuarios Usua_ModificacionNavigation { get; set; }

    public virtual ICollection<tbMetasPorEmpleados> tbMetasPorEmpleados { get; set; } = new List<tbMetasPorEmpleados>();
}