// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIDCOP_Backend.Entities.Entities;

public partial class tbMetasPorEmpleados
{
    public int MeEm_Id { get; set; }

    public decimal MeEm_ProgresoIngresos { get; set; }

    public decimal MeEm_ProgresoUnidades { get; set; }

    public int? Meta_Id { get; set; }

    public int? Vend_Id { get; set; }

    public bool MeEm_Estado { get; set; }

    public int Usua_Creacion { get; set; }

    public DateTime MeEm_FechaCreacion { get; set; }

    public int? Usua_Modificacion { get; set; }

    public DateTime? MeEm_FechaModificacion { get; set; }

    public virtual tbMetas Meta { get; set; }

    public virtual tbUsuarios Usua_CreacionNavigation { get; set; }

    public virtual tbUsuarios Usua_ModificacionNavigation { get; set; }

    public virtual tbVendedores Vend { get; set; }
}