// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace SIDCOP_Backend.Entities.Entities;

public partial class tbModelos
{
    public int Mode_Id { get; set; }

    public int MaVe_Id { get; set; }

    public string Mode_Descripcion { get; set; }

    public int Usua_Creacion { get; set; }

    public DateTime Mode_FechaCreacion { get; set; }

    public int? Usua_Modificacion { get; set; }

    public DateTime? Mode_FechaModificacion { get; set; }

    public bool Mode_Estado { get; set; }
    [NotMapped]
    public string MaVe_Marca { get; set; }
    [NotMapped]
    public string UsuarioCreacion { get; set; }

    [NotMapped]
    public string UsuarioModificacion { get; set; }
    [NotMapped]
    public int? Secuencia { get; set; }

    public virtual tbMarcasVehiculos MaVe { get; set; }

    public virtual tbUsuarios Usua_CreacionNavigation { get; set; }

    public virtual tbUsuarios Usua_ModificacionNavigation { get; set; }

    public virtual ICollection<tbBodegas> tbBodegas { get; set; } = new List<tbBodegas>();
}