// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIDCOP_Backend.Entities.Entities;

public partial class tbParentescos
{
    public int Pare_Id { get; set; }

    public string Pare_Descripcion { get; set; }

    public int Usua_Creacion { get; set; }

    public DateTime Pare_FechaCreacion { get; set; }

    public int? Usua_Modificacion { get; set; }

    public DateTime? Pare_FechaModificacion { get; set; }

    public virtual tbUsuarios Usua_CreacionNavigation { get; set; }

    public virtual tbUsuarios Usua_ModificacionNavigation { get; set; }

    public virtual ICollection<tbAvales> tbAvales { get; set; } = new List<tbAvales>();
}