// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace SIDCOP_Backend.Entities.Entities;

public partial class tbPagosCuentasPorCobrar
{
    public int Pago_Id { get; set; }

    public int CPCo_Id { get; set; }

    public DateTime Pago_Fecha { get; set; }

    public decimal Pago_Monto { get; set; }

    public string Pago_FormaPago { get; set; }

    public string Pago_NumeroReferencia { get; set; }

    public string Pago_Observaciones { get; set; }

    public int Usua_Creacion { get; set; }

    public DateTime Pago_FechaCreacion { get; set; }

    public int? Usua_Modificacion { get; set; }

    public DateTime? Pago_FechaModificacion { get; set; }

    public bool Pago_Estado { get; set; }

    public bool Pago_Anulado { get; set; }

    // Propiedades de navegación
    [NotMapped]
    public string UsuarioCreacion { get; set; }

    [NotMapped]
    public string UsuarioModificacion { get; set; }

    [NotMapped]
    public int Clie_Id { get; set; }

    [NotMapped]
    public string Clie_NombreCompleto { get; set; }

    [NotMapped]
    public string Clie_RTN { get; set; }

    [NotMapped]
    public int Fact_Id { get; set; }

    [NotMapped]
    public string Fact_Numero { get; set; }

    // Relaciones de navegación
    public virtual tbCuentasPorCobrar CPCo { get; set; }

    public virtual tbUsuarios Usua_CreacionNavigation { get; set; }

    public virtual tbUsuarios Usua_ModificacionNavigation { get; set; }
}
