// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIDCOP_Backend.Entities.Entities;

public partial class tbPaises
{
    public string Pais_Codigo { get; set; }

    public string Pais_Descripcion { get; set; }

    public int Usua_Creacion { get; set; }

    public DateTime Pais_FechaCreacion { get; set; }

    public int? Usua_Modificacion { get; set; }

    public DateTime? Pais_FechaModificacion { get; set; }

    public virtual tbUsuarios Usua_CreacionNavigation { get; set; }

    public virtual tbUsuarios Usua_ModificacionNavigation { get; set; }

    public virtual ICollection<tbDepartamentos> tbDepartamentos { get; set; } = new List<tbDepartamentos>();
}