// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIDCOP_Backend.Entities.Entities;

public partial class tbPantallas
{
    public int Pant_Id { get; set; }

    public string Pant_Descripcion { get; set; }

    public bool Pant_EsPadre { get; set; }

    public int? Pant_Padre { get; set; }

    public string Pant_Icon { get; set; }

    public string Pant_Ruta { get; set; }

    public virtual ICollection<tbPantallas> InversePant_PadreNavigation { get; set; } = new List<tbPantallas>();

    public virtual tbPantallas Pant_PadreNavigation { get; set; }

    public virtual ICollection<tbAccionesPorPantalla> tbAccionesPorPantalla { get; set; } = new List<tbAccionesPorPantalla>();
}