// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIDCOP_Backend.Entities.Entities;

public partial class tbPedidosDetalle
{
    public int PeDe_Id { get; set; }

    public int Pedi_Id { get; set; }

    public int Prod_Id { get; set; }

    public int PeDe_Cantidad { get; set; }

    public decimal PeDe_ProdPrecio { get; set; }

    public decimal? PeDe_ProdPrecioFinal { get; set; }

    public int Usua_Creacion { get; set; }

    public DateTime PeDe_FechaCreacion { get; set; }

    public int? Usua_Modificacion { get; set; }

    public DateTime? PeDe_FechaModificacion { get; set; }

    public bool PeDe_Estado { get; set; }

    public virtual tbPedidos Pedi { get; set; }

    public virtual tbProductos Prod { get; set; }

    public virtual tbUsuarios Usua_CreacionNavigation { get; set; }

    public virtual tbUsuarios Usua_ModificacionNavigation { get; set; }
}