// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIDCOP_Backend.Entities.Entities;

public partial class tbPedidosHistorial
{
    public int HiPe_Id { get; set; }

    public int? Pedi_Id { get; set; }

    public int? DiCl_Id { get; set; }

    public int? Vend_Id { get; set; }

    public DateTime? Pedi_FechaPedido { get; set; }

    public DateTime? Pedi_FechaEntrega { get; set; }

    public bool? Pedi_Estado { get; set; }

    public string HiPe_Accion { get; set; }

    public DateTime HiPe_FechaAccion { get; set; }

    public int HiPe_UsuarioAccion { get; set; }
}