// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace SIDCOP_Backend.Entities.Entities;

public partial class tbPedidos
{

    [NotMapped]

    public int? Secuencia { get; set; }

    public int Pedi_Id { get; set; }

    public int DiCl_Id { get; set; }

    public int Vend_Id { get; set; }

    public DateTime Pedi_FechaPedido { get; set; }

    public DateTime? Pedi_FechaEntrega { get; set; }

    public int Usua_Creacion { get; set; }

    public DateTime Pedi_FechaCreacion { get; set; }

    public int? Usua_Modificacion { get; set; }

    public DateTime? Pedi_FechaModificacion { get; set; }

    public bool Pedi_Estado { get; set; }

    [NotMapped]
    public string? DetallesJson { get; set; }


    [NotMapped]
    public int? Clie_Id { get; set; }


    [NotMapped]
    public string? Clie_Codigo { get; set; }

    [NotMapped]
    public string? Clie_NombreNegocio { get; set; }

    [NotMapped]
    public string? Clie_Nombres { get; set; }

    [NotMapped]
    public string? Clie_Apellidos { get; set; }

    [NotMapped]
    public string? Colo_Descripcion { get; set; }

    [NotMapped]
    public string? Muni_Descripcion { get; set; }

    [NotMapped]
    public string? Depa_Descripcion { get; set; }

    [NotMapped]
    public string? DiCl_DireccionExacta { get; set; }


    [NotMapped]
    public string? Vend_Nombres { get; set; }

    [NotMapped]
    public string? Vend_Apellidos { get; set; }

    [NotMapped]
    public string? UsuarioCreacion { get; set; }

    [NotMapped]
    public string? UsuarioModificacion { get; set; }

    [NotMapped]
    public string? Prod_Codigo { get; set; }

    [NotMapped]
    public string? Prod_Descripcion { get; set; }

    [NotMapped]
    public decimal? PeDe_ProdPrecio { get; set; }

    [NotMapped]
    public int? PeDe_Cantidad { get; set; }


    [NotMapped]
    public List<PedidoDetalleDTO> Detalles { get; set; }

    public virtual tbDireccionesPorCliente DiCl { get; set; }

    public virtual tbUsuarios Usua_CreacionNavigation { get; set; }

    public virtual tbUsuarios Usua_ModificacionNavigation { get; set; }

    public virtual tbVendedores Vend { get; set; }

    public virtual ICollection<tbPedidosDetalle> tbPedidosDetalle { get; set; } = new List<tbPedidosDetalle>();
}

public class PedidoDetalleDTO
{
    public int Prod_Id { get; set; }
    public int PeDe_Cantidad { get; set; }
    public decimal PeDe_ProdPrecio { get; set; }
}