// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace SIDCOP_Backend.Entities.Entities;

public partial class tbPermisos
{
    public int Perm_Id { get; set; }

    public int Role_Id { get; set; }

    public int AcPa_Id { get; set; }

    public int Usua_Creacion { get; set; }

    public DateTime Perm_FechaCreacion { get; set; }

    public int? Usua_Modificacion { get; set; }

    public DateTime? Perm_FechaModificacion { get; set; }
    [NotMapped]
    public string Role_Descripcion { get; set; }

    [NotMapped]
    public int Pant_Id { get; set; }

    [NotMapped]
    public string Pant_Descripcion { get; set; }

    [NotMapped]
    public int Acci_Id { get; set; }

    [NotMapped]
    public string Acci_Descripcion { get; set; }

    public virtual tbAccionesPorPantalla AcPa { get; set; }

    public virtual tbRoles Role { get; set; }

    public virtual tbUsuarios Usua_CreacionNavigation { get; set; }

    public virtual tbUsuarios Usua_ModificacionNavigation { get; set; }
}