// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIDCOP_Backend.Entities.Entities;

public partial class tbPedidos
{
    public int Pedi_Id { get; set; }

    public int DiCl_Id { get; set; }

    public int Vend_Id { get; set; }

    public DateTime Pedi_FechaPedido { get; set; }

    public DateTime? Pedi_FechaEntrega { get; set; }

    public int Usua_Creacion { get; set; }

    public DateTime Pedi_FechaCreacion { get; set; }

    public int? Usua_Modificacion { get; set; }

    public DateTime? Pedi_FechaModificacion { get; set; }

    public bool Pedi_Estado { get; set; }

    public virtual tbDireccionesPorCliente DiCl { get; set; }

    public virtual tbUsuarios Usua_CreacionNavigation { get; set; }

    public virtual tbUsuarios Usua_ModificacionNavigation { get; set; }

    public virtual tbVendedores Vend { get; set; }

    public virtual ICollection<tbPedidosDetalle> tbPedidosDetalle { get; set; } = new List<tbPedidosDetalle>();
}