// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIDCOP_Backend.Entities.Entities;

public partial class tbPedidosDetalleHistorial
{
    public int HPeD_Id { get; set; }

    public int? PeDe_Id { get; set; }

    public int? Pedi_Id { get; set; }

    public int? Prod_Id { get; set; }

    public int? PeDe_Cantidad { get; set; }

    public decimal? PeDe_ProdPrecio { get; set; }

    public bool? PeDe_Estado { get; set; }

    public string HPeD_Accion { get; set; }

    public DateTime HPeD_FechaAccion { get; set; }

    public int HPeD_UsuarioAccion { get; set; }
}