// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIDCOP_Backend.Entities.Entities;

public partial class tbProductosHistorial
{
    public int HPro_Id { get; set; }

    public int? Prod_Id { get; set; }

    public string Prod_Codigo { get; set; }

    public string Prod_CodigoBarra { get; set; }

    public string Prod_Descripcion { get; set; }

    public string Prom_DescripcionCorta { get; set; }

    public string Prod_Imagen { get; set; }

    public int? Subc_Id { get; set; }

    public int? Marc_Id { get; set; }

    public int? Prov_Id { get; set; }

    public int? Impu_Id { get; set; }

    public decimal? Prod_PrecioUnitario { get; set; }

    public decimal? Prod_CostoTotal { get; set; }

    public string Prod_PagaImpuesto { get; set; }

    public string Prod_EsPromo { get; set; }

    public bool? Prom_Estado { get; set; }

    public string HPro_Accion { get; set; }

    public DateTime HPro_FechaAccion { get; set; }

    public int HPro_UsuarioAccion { get; set; }
}