// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIDCOP_Backend.Entities.Entities;

public partial class tbPreciosPorProductoHistorial
{
    public int HiPP_Id { get; set; }

    public int? PreP_Id { get; set; }

    public int? Prod_Id { get; set; }

    public int? Clie_Id { get; set; }

    public decimal? PreP_PrecioContado { get; set; }

    public decimal? PreP_PrecioCredito { get; set; }

    public int? PreP_InicioEscala { get; set; }

    public int? PreP_FinEscala { get; set; }

    public int? PreP_ListaPrecios { get; set; }

    public bool? PreP_Estado { get; set; }

    public string HiPP_Accion { get; set; }

    public DateTime HiPP_FechaAccion { get; set; }

    public int HiPP_UsuarioAccion { get; set; }
}