// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace SIDCOP_Backend.Entities.Entities;

public partial class tbProveedores
{
    public int Prov_Id { get; set; }

    public string Prov_Codigo { get; set; }

    public string Prov_NombreEmpresa { get; set; }

    public string Prov_NombreContacto { get; set; }

    public int Colo_Id { get; set; }

    public string Prov_DireccionExacta { get; set; }

    public string Prov_Telefono { get; set; }

    public string Prov_Correo { get; set; }

    public string Prov_Observaciones { get; set; }

    public int Usua_Creacion { get; set; }

    public DateTime Prov_FechaCreacion { get; set; }

    public int? Usua_Modificacion { get; set; }

    public DateTime? Prov_FechaModificacion { get; set; }

    public bool Prov_Estado { get; set; }

    [NotMapped]
    public string Colo_Descripcion { get; set; }
    [NotMapped]
    public string Muni_Descripcion { get; set; }

    [NotMapped]
    public string Depa_Descripcion { get; set; }
    [NotMapped]
    public string UsuarioCreacion { get; set; }
    [NotMapped]
    public string UsuarioModificacion { get; set; }

    [NotMapped]
    public int Secuencia { get; set; }

    public virtual tbColonias Colo { get; set; }

    public virtual tbUsuarios Usua_CreacionNavigation { get; set; }

    public virtual tbUsuarios Usua_ModificacionNavigation { get; set; }

    public virtual ICollection<tbProductos> tbProductos { get; set; } = new List<tbProductos>();
}