// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIDCOP_Backend.Entities.Entities;

public partial class tbPromocionesPorClientes
{
    public int PrCl_Id { get; set; }

    public int Prom_Id { get; set; }

    public int Clie_Id { get; set; }

    public int Usua_Creacion { get; set; }

    public DateTime PrCl_FechaCreacion { get; set; }

    public int? Usua_Modificacion { get; set; }

    public DateTime? PrCl_FechaModificacion { get; set; }

    public virtual tbClientes Clie { get; set; }

    public virtual tbProductos Prom { get; set; }

    public virtual tbUsuarios Usua_CreacionNavigation { get; set; }

    public virtual tbUsuarios Usua_ModificacionNavigation { get; set; }
}