// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIDCOP_Backend.Entities.Entities;

public partial class tbPromocionesDetalleHistorial
{
    public int HPrD_Id { get; set; }

    public int? PrDe_Id { get; set; }

    public int? Prom_Id { get; set; }

    public int? Prod_Id { get; set; }

    public bool? PrDe_Estado { get; set; }

    public string HPrD_Accion { get; set; }

    public DateTime HPrD_FechaAccion { get; set; }

    public int HPrD_UsuarioAccion { get; set; }
}