// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIDCOP_Backend.Entities.Entities;

public partial class tbProductos
{
    public int Prod_Id { get; set; }

    public string Prod_Codigo { get; set; }

    public string Prod_CodigoBarra { get; set; }

    public string Prod_Descripcion { get; set; }

    public string Prod_DescripcionCorta { get; set; }

    public string Prod_Imagen { get; set; }

    public int Subc_Id { get; set; }

    public int Marc_Id { get; set; }

    public int Prov_Id { get; set; }

    public int Impu_Id { get; set; }

    public decimal? Prod_PrecioUnitario { get; set; }

    public decimal? Prod_CostoTotal { get; set; }

    public string Prod_PagaImpuesto { get; set; }

    public int? Prod_PromODesc { get; set; }

    public string Prod_EsPromo { get; set; }

    public bool Prod_Estado { get; set; }

    public int Usua_Creacion { get; set; }

    public DateTime Prod_FechaCreacion { get; set; }

    public int? Usua_Modificacion { get; set; }

    public DateTime? Prod_FechaModificacion { get; set; }

    [NotMapped]
    public int? Secuencia { get; set; }

    [NotMapped]
    public int Cate_Id { get; set; }
    [NotMapped]
    public string Cate_Descripcion { get; set; }


    [NotMapped]
    public string? Marc_Descripcion { get; set; }

    [NotMapped]
    public string? Prov_NombreEmpresa { get; set; }

    [NotMapped]
    public string? Subc_Descripcion { get; set; }

    [NotMapped]
    public string? Impu_Descripcion { get; set; }

    [NotMapped]
    public string? UsuarioCreacion { get; set; }

    [NotMapped]
    public string? UsuarioModificacion { get; set; }



    public virtual tbImpuestos Impu { get; set; }

    public virtual tbMarcas Marc { get; set; }

    public virtual tbProveedores Prov { get; set; }

    public virtual tbSubcategorias Subc { get; set; }

    public virtual tbUsuarios Usua_CreacionNavigation { get; set; }

    public virtual tbUsuarios Usua_ModificacionNavigation { get; set; }

    public virtual ICollection<tbDevolucionesDetalle> tbDevolucionesDetalle { get; set; } = new List<tbDevolucionesDetalle>();

    public virtual ICollection<tbFacturasDetalle> tbFacturasDetalle { get; set; } = new List<tbFacturasDetalle>();

    public virtual ICollection<tbInventarioBodegas> tbInventarioBodegas { get; set; } = new List<tbInventarioBodegas>();

    public virtual ICollection<tbInventarioSucursales> tbInventarioSucursales { get; set; } = new List<tbInventarioSucursales>();

    public virtual ICollection<tbPedidosDetalle> tbPedidosDetalle { get; set; } = new List<tbPedidosDetalle>();

    public virtual ICollection<tbPreciosPorProducto> tbPreciosPorProducto { get; set; } = new List<tbPreciosPorProducto>();

    public virtual ICollection<tbRecargasDetalle> tbRecargasDetalle { get; set; } = new List<tbRecargasDetalle>();

    public virtual ICollection<tbTrasladosDetalle> tbTrasladosDetalle { get; set; } = new List<tbTrasladosDetalle>();
}