// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace SIDCOP_Backend.Entities.Entities;

public partial class tbPuntosEmision
{
    [NotMapped]
    public int Secuencia { get; set; }

    [NotMapped]
    public String Estado { get; set; }

    [NotMapped]
    public String UsuarioCreacion { get; set; }

    [NotMapped]
    public String UsuarioModificacion { get; set; }

    public int PuEm_Id { get; set; }

    public string PuEm_Codigo { get; set; }

    public string PuEm_Descripcion { get; set; }

    public int Usua_Creacion { get; set; }

    public DateTime PuEm_FechaCreacion { get; set; }

    public int? Usua_Modificacion { get; set; }

    public DateTime? PuEm_FechaModificacion { get; set; }

    public bool PuEm_Estado { get; set; }

    public int? Sucu_Id { get; set; }

    public virtual tbSucursales Sucu { get; set; }

    public virtual tbUsuarios Usua_CreacionNavigation { get; set; }

    public virtual tbUsuarios Usua_ModificacionNavigation { get; set; }

    public virtual ICollection<tbRegistrosCAI> tbRegistrosCAI { get; set; } = new List<tbRegistrosCAI>();
}