// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace SIDCOP_Backend.Entities.Entities;

public partial class tbRecargas
{
    public int Reca_Id { get; set; }

    [NotMapped]
    public string Recarga { get; set; }

    public int Vend_Id { get; set; }

    public int Bode_Id { get; set; }



    public DateTime Reca_Fecha { get; set; }

    public string Reca_Observaciones { get; set; }

    public int? Usua_Confirmacion { get; set; }

    public int Usua_Creacion { get; set; }

    public DateTime Reca_FechaCreacion { get; set; }

    public int? Usua_Modificacion { get; set; }

    public DateTime? Reca_FechaModificacion { get; set; }

    public bool Reca_Estado { get; set; }

    public string Reca_Confirmacion { get; set; }

    [NotMapped]
    public string? Bode_Descripcion { get; set; }

    [NotMapped]
    public string? Prod_DescripcionCorta { get; set; }

    [NotMapped]
    public string? Prod_Codigo { get; set; }

    [NotMapped]
    public string? Prod_Imagen { get; set; }

    [NotMapped]
    public string? ReDe_Observaciones { get; set; }

    [NotMapped]
    public int? ReDe_Cantidad { get; set; }
    [NotMapped]
    public string? DetalleProductos { get; set; }

    [NotMapped]
    public int? Prod_Id { get; set; }

    [NotMapped]
    public List<RecargaDetalleDTO> Detalles { get; set; }

    public virtual tbBodegas Bode { get; set; }

    public virtual tbUsuarios Usua_ConfirmacionNavigation { get; set; }

    public virtual tbUsuarios Usua_CreacionNavigation { get; set; }

    public virtual tbUsuarios Usua_ModificacionNavigation { get; set; }

    public virtual tbVendedores Vend { get; set; }

    public virtual ICollection<tbRecargasDetalle> tbRecargasDetalle { get; set; } = new List<tbRecargasDetalle>();
}

public class RecargaDetalleDTO
{
    public int Prod_Id { get; set; }
    public int ReDe_Cantidad { get; set; }
    public string ReDe_Observaciones { get; set; }

}