// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIDCOP_Backend.Entities.Entities;

public partial class tbRegistrosCAI
{
    public int RegC_Id { get; set; }

    public string RegC_Descripcion { get; set; }

    public int? Sucu_Id { get; set; }

    public int? PuEm_Id { get; set; }

    public int NCai_Id { get; set; }

    public string RegC_RangoInicial { get; set; }

    public string RegC_RangoFinal { get; set; }

    public DateTime RegC_FechaInicialEmision { get; set; }

    public DateTime RegC_FechaFinalEmision { get; set; }

    public int Usua_Creacion { get; set; }

    public DateTime RegC_FechaCreacion { get; set; }

    public int? Usua_Modificacion { get; set; }

    public DateTime? RegC_FechaModificacion { get; set; }

    public bool RegC_Estado { get; set; }

    public virtual tbCAIs NCai { get; set; }

    public virtual tbPuntosEmision PuEm { get; set; }

    public virtual tbSucursales Sucu { get; set; }

    public virtual tbUsuarios Usua_CreacionNavigation { get; set; }

    public virtual tbUsuarios Usua_ModificacionNavigation { get; set; }

    public virtual ICollection<tbBodegas> tbBodegas { get; set; } = new List<tbBodegas>();

    public virtual ICollection<tbFacturas> tbFacturas { get; set; } = new List<tbFacturas>();
}