// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIDCOP_Backend.Entities.Entities;

public partial class tbRecargasDetalle
{
    public int ReDe_Id { get; set; }

    public int Reca_Id { get; set; }

    public int Prod_Id { get; set; }

    public int ReDe_Cantidad { get; set; }

    public string ReDe_Observaciones { get; set; }

    public int Usua_Creacion { get; set; }

    public DateTime ReDe_FechaCreacion { get; set; }

    public int? Usua_Modificacion { get; set; }

    public DateTime? ReDe_FechaModificacion { get; set; }

    public virtual tbProductos Prod { get; set; }

    public virtual tbRecargas Reca { get; set; }

    public virtual tbUsuarios Usua_CreacionNavigation { get; set; }

    public virtual tbUsuarios Usua_ModificacionNavigation { get; set; }
}