// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIDCOP_Backend.Entities.Entities;

public partial class tbRecargasHistorial
{
    public int HRec_Id { get; set; }

    public int? Reca_Id { get; set; }

    public int? Vend_Id { get; set; }

    public int? Bode_Id { get; set; }

    public int? Tras_Id { get; set; }

    public DateTime? Reca_Fecha { get; set; }

    public string Reca_Observaciones { get; set; }

    public int? Usua_Confirmacion { get; set; }

    public bool? Reca_Confirmacion { get; set; }

    public bool? Reca_Estado { get; set; }

    public string HRec_Accion { get; set; }

    public DateTime HRec_FechaAccion { get; set; }

    public int HRec_UsuarioAccion { get; set; }
}