// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIDCOP_Backend.Entities.Entities;

public partial class tbRecargasDetalleHistorial
{
    public int HReD_Id { get; set; }

    public int? ReDe_Id { get; set; }

    public int? Reca_Id { get; set; }

    public int? Prod_Id { get; set; }

    public int? ReDe_Cantidad { get; set; }

    public string ReDe_Observaciones { get; set; }

    public string HReD_Accion { get; set; }

    public DateTime HReD_FechaAccion { get; set; }

    public int HReD_UsuarioAccion { get; set; }
}