// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIDCOP_Backend.Entities.Entities;

public partial class tbRecargas
{
    public int Reca_Id { get; set; }

    public int Empl_Id { get; set; }

    public int Bode_Id { get; set; }

    public int? Tras_Id { get; set; }

    public DateTime Reca_Fecha { get; set; }

    public string Reca_Observaciones { get; set; }

    public bool Reca_Confirmacion { get; set; }

    public int? Usua_Confirmacion { get; set; }

    public int Usua_Creacion { get; set; }

    public DateTime Reca_FechaCreacion { get; set; }

    public int? Usua_Modificacion { get; set; }

    public DateTime? Reca_FechaModificacion { get; set; }

    public bool Reca_Estado { get; set; }

    public virtual tbBodegas Bode { get; set; }

    public virtual tbEmpleados Empl { get; set; }

    public virtual tbTraslados Tras { get; set; }

    public virtual tbUsuarios Usua_ConfirmacionNavigation { get; set; }

    public virtual tbUsuarios Usua_CreacionNavigation { get; set; }

    public virtual tbUsuarios Usua_ModificacionNavigation { get; set; }

    public virtual ICollection<tbRecargasDetalle> tbRecargasDetalle { get; set; } = new List<tbRecargasDetalle>();
}