// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace SIDCOP_Backend.Entities.Entities;

public partial class tbRutas
{
    public int Ruta_Id { get; set; }

    public string Ruta_Codigo { get; set; }

    public string Ruta_Descripcion { get; set; }

    public string Ruta_Observaciones { get; set; }

    public int Usua_Creacion { get; set; }

    public DateTime Ruta_FechaCreacion { get; set; }

    public int? Usua_Modificacion { get; set; }

    public DateTime? Ruta_FechaModificacion { get; set; }

    public bool Ruta_Estado { get; set; }

    [NotMapped]
    public int? Secuencia { get; set; }

    [NotMapped]
    public string? UsuarioCreacion { get; set; }

    [NotMapped]
    public string? UsuarioModificacion { get; set; }

    public virtual tbUsuarios Usua_CreacionNavigation { get; set; }

    public virtual tbUsuarios Usua_ModificacionNavigation { get; set; }

    public virtual ICollection<tbClientes> tbClientes { get; set; } = new List<tbClientes>();

    public virtual ICollection<tbVendedoresPorRuta> tbVendedoresPorRuta { get; set; } = new List<tbVendedoresPorRuta>();
}