// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIDCOP_Backend.Entities.Entities;

public partial class tbSubcategorias
{
    public int Subc_Id { get; set; }

    public string Subc_Descripcion { get; set; }

    public int Cate_Id { get; set; }

    public int Usua_Creacion { get; set; }

    public DateTime Subc_FechaCreacion { get; set; }

    public int? Usua_Modificacion { get; set; }

    public DateTime? Subc_FechaModificacion { get; set; }

    public bool Subc_Estado { get; set; }

    //public virtual tbCategorias Cate { get; set; }

    //public virtual tbUsuarios Usua_CreacionNavigation { get; set; }

    //public virtual tbUsuarios Usua_ModificacionNavigation { get; set; }

    //public virtual ICollection<tbProductos> tbProductos { get; set; } = new List<tbProductos>();
}