// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace SIDCOP_Backend.Entities.Entities;

public partial class tbSucursales
{
    public int Sucu_Id { get; set; }

    public string Sucu_Descripcion { get; set; }

    public int Colo_Id { get; set; }

    public string Sucu_DireccionExacta { get; set; }

    public string Sucu_Telefono1 { get; set; }

    public string Sucu_Telefono2 { get; set; }

    public string Sucu_Correo { get; set; }

    public int Usua_Creacion { get; set; }

    public DateTime Sucu_FechaCreacion { get; set; }

    public int? Usua_Modificacion { get; set; }

    public DateTime? Sucu_FechaModificacion { get; set; }

    public bool Sucu_Estado { get; set; }

    [NotMapped]
    public string? Colo_Descripcion { get; set; }

    [NotMapped]
    public string? Muni_Codigo { get; set; }

    [NotMapped]
    public string? Muni_Descripcion { get; set; }

    [NotMapped]
    public string? Depa_Codigo { get; set; }

    [NotMapped]
    public string? Depa_Descripcion { get; set; }

    [NotMapped]
    public string? UsuarioCreacion { get; set; }

    [NotMapped]
    public string? UsuarioModificacion { get; set; }

    [NotMapped]
    public int? Secuencia { get; set; }

    public virtual tbColonias Colo { get; set; }

    public virtual tbUsuarios Usua_CreacionNavigation { get; set; }

    public virtual tbUsuarios Usua_ModificacionNavigation { get; set; }

    public virtual ICollection<tbBodegas> tbBodegas { get; set; } = new List<tbBodegas>();

    public virtual ICollection<tbEmpleados> tbEmpleados { get; set; } = new List<tbEmpleados>();

    public virtual ICollection<tbInventarioSucursales> tbInventarioSucursales { get; set; } = new List<tbInventarioSucursales>();

    public virtual ICollection<tbPuntosEmision> tbPuntosEmision { get; set; } = new List<tbPuntosEmision>();

    public virtual ICollection<tbRegistrosCAI> tbRegistrosCAI { get; set; } = new List<tbRegistrosCAI>();

    public virtual ICollection<tbTraslados> tbTraslados { get; set; } = new List<tbTraslados>();

    public virtual ICollection<tbVendedores> tbVendedores { get; set; } = new List<tbVendedores>();
}