// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace SIDCOP_Backend.Entities.Entities;

public partial class tbTiposDeVendedor
{
    public int TiVe_Id { get; set; }

    public string TiVe_TipoVendedor { get; set; }

    public int Usua_Creacion { get; set; }

    public DateTime TiVe_FechaCreacion { get; set; }

    public int? Usua_Modificacion { get; set; }

    public DateTime? TiVe_FechaModificacion { get; set; }

    [NotMapped]
    public string? Secuencia { get; set; }


    [NotMapped]
    public string? UsuarioCreacion { get; set; }

      [NotMapped]
    public string? UsuarioModificacion { get; set; }

    public virtual tbUsuarios Usua_CreacionNavigation { get; set; }

    public virtual tbUsuarios Usua_ModificacionNavigation { get; set; }

    public virtual ICollection<tbVendedores> tbVendedores { get; set; } = new List<tbVendedores>();
}