// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIDCOP_Backend.Entities.Entities;

public partial class tbTiposDeVivienda
{
    public int TiVi_Id { get; set; }

    public string TiVi_Descripcion { get; set; }

    public string TiVi_Observaciones { get; set; }

    public int Usua_Creacion { get; set; }

    public DateTime TiVi_FechaCreacion { get; set; }

    public int? Usua_Modificacion { get; set; }

    public DateTime? TiVi_FechaModificacion { get; set; }

    public bool TiVi_Estado { get; set; }

    public virtual tbUsuarios Usua_CreacionNavigation { get; set; }

    public virtual tbUsuarios Usua_ModificacionNavigation { get; set; }

    public virtual ICollection<tbAvales> tbAvales { get; set; } = new List<tbAvales>();

    public virtual ICollection<tbClientes> tbClientes { get; set; } = new List<tbClientes>();
}