// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIDCOP_Backend.Entities.Entities;

public partial class tbTrasladosHistorial
{
    public int HTra_Id { get; set; }

    public int? Tras_Id { get; set; }

    public int? Tras_Origen { get; set; }

    public int? Tras_Destino { get; set; }

    public DateTime? Tras_Fecha { get; set; }

    public string Tras_Observaciones { get; set; }

    public bool? Tras_Estado { get; set; }

    public string HTra_Accion { get; set; }

    public DateTime HTra_FechaAccion { get; set; }

    public int HTra_UsuarioAccion { get; set; }
}