// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIDCOP_Backend.Entities.Entities;

public partial class tbTrasladosDetalleHistorial
{
    public int HTDe_Id { get; set; }

    public int? TrDe_Id { get; set; }

    public int? Tras_Id { get; set; }

    public int? Prod_Id { get; set; }

    public int? TrDe_Cantidad { get; set; }

    public string TrDe_Observaciones { get; set; }

    public string HTDe_Accion { get; set; }

    public DateTime HTDe_FechaAccion { get; set; }

    public int HTDe_UsuarioAccion { get; set; }
}