// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace SIDCOP_Backend.Entities.Entities;

public partial class tbTraslados
{
    public int Tras_Id { get; set; }

    public int Tras_Origen { get; set; }

    public int Tras_Destino { get; set; }

    public DateTime Tras_Fecha { get; set; }

    public string Tras_Observaciones { get; set; }

    public int Usua_Creacion { get; set; }

    [NotMapped]
    public string UsuaCreacion { get; set; }

    public DateTime Tras_FechaCreacion { get; set; }

    public int? Usua_Modificacion { get; set; }

    [NotMapped]
    public string UsuaModificacion { get; set; }

    public DateTime? Tras_FechaModificacion { get; set; }

    public bool Tras_Estado { get; set; }

    public bool? Tras_EsRecarga { get; set; }

    public int? Reca_Id { get; set; }

    [NotMapped]
    public string Origen { get; set; }

    [NotMapped]
    public string Destino { get; set; }

    [NotMapped]
    public int? Secuencia { get; set; }

    public virtual tbBodegas Tras_DestinoNavigation { get; set; }

    public virtual tbSucursales Tras_OrigenNavigation { get; set; }

    public virtual tbUsuarios Usua_CreacionNavigation { get; set; }

    public virtual tbUsuarios Usua_ModificacionNavigation { get; set; }

    public virtual ICollection<tbTrasladosDetalle> tbTrasladosDetalle { get; set; } = new List<tbTrasladosDetalle>();
}