// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;

namespace SIDCOP_Backend.Entities.Entities;

public partial class tbUnidadesDePeso
{
    public int UnPe_Id { get; set; }

    public string UnPe_Descripcion { get; set; }

    public int Usua_Creacion { get; set; }

    public DateTime UnPe_FechaCreacion { get; set; }

    public int? Usua_Modificacion { get; set; }

    [NotMapped]
    public string UsuarioCreacion { get; set; }
    [NotMapped]
    public string UsuarioModificacion { get; set; }


    public DateTime? UnPe_FechaModificacion { get; set; }

    public virtual tbUsuarios Usua_CreacionNavigation { get; set; }

    public virtual tbUsuarios Usua_ModificacionNavigation { get; set; }
}