// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace SIDCOP_Backend.Entities.Entities;

public partial class tbUsuarios
{
    public int Usua_Id { get; set; }

    public string Usua_Usuario { get; set; }

    public byte[] Usua_Clave { get; set; }

    public int Role_Id { get; set; }

    [NotMapped]
    public string Role_Descripcion { get; set; }

    public int Usua_IdPersona { get; set; }

    public bool Usua_EsVendedor { get; set; }

    public bool Usua_EsAdmin { get; set; }

    public string Usua_Imagen { get; set; }

    public int Usua_Creacion { get; set; }

    public DateTime Usua_FechaCreacion { get; set; }

    public int? Usua_Modificacion { get; set; }

    public DateTime? Usua_FechaModificacion { get; set; }

    public bool Usua_Estado { get; set; }

    [NotMapped]
    public string? Correo { get; set; }


    [NotMapped]
    public string? PermisosJson { get; set; }

    [NotMapped]
    public string? NombreCompleto { get; set; }


    public virtual ICollection<tbUsuarios> InverseUsua_CreacionNavigation { get; set; } = new List<tbUsuarios>();

    public virtual ICollection<tbUsuarios> InverseUsua_ModificacionNavigation { get; set; } = new List<tbUsuarios>();

    public virtual tbRoles Role { get; set; }

    public virtual tbUsuarios Usua_CreacionNavigation { get; set; }

    public virtual tbUsuarios Usua_ModificacionNavigation { get; set; }


    public virtual ICollection<tbBodegas> tbBodegasUsua_CreacionNavigation { get; set; } = new List<tbBodegas>();

    public virtual ICollection<tbBodegas> tbBodegasUsua_ModificacionNavigation { get; set; } = new List<tbBodegas>();

    public virtual ICollection<tbCAIs> tbCAIsUsua_CreacionNavigation { get; set; } = new List<tbCAIs>();

    public virtual ICollection<tbCAIs> tbCAIsUsua_ModificacionNavigation { get; set; } = new List<tbCAIs>();

    public virtual ICollection<tbCanales> tbCanalesUsua_CreacionNavigation { get; set; } = new List<tbCanales>();

    public virtual ICollection<tbCanales> tbCanalesUsua_ModificacionNavigation { get; set; } = new List<tbCanales>();

    public virtual ICollection<tbCargos> tbCargosUsua_CreacionNavigation { get; set; } = new List<tbCargos>();

    public virtual ICollection<tbCargos> tbCargosUsua_ModificacionNavigation { get; set; } = new List<tbCargos>();

    public virtual ICollection<tbCategorias> tbCategoriasUsua_CreacionNavigation { get; set; } = new List<tbCategorias>();

    public virtual ICollection<tbCategorias> tbCategoriasUsua_ModificacionNavigation { get; set; } = new List<tbCategorias>();

    public virtual ICollection<tbClientes> tbClientesUsua_CreacionNavigation { get; set; } = new List<tbClientes>();

    public virtual ICollection<tbClientes> tbClientesUsua_ModificacionNavigation { get; set; } = new List<tbClientes>();

    public virtual ICollection<tbColonias> tbColoniasUsua_CreacionNavigation { get; set; } = new List<tbColonias>();

    public virtual ICollection<tbColonias> tbColoniasUsua_ModificacionNavigation { get; set; } = new List<tbColonias>();

    public virtual ICollection<tbConfiguracionFacturas> tbConfiguracionFacturasUsua_CreacionNavigation { get; set; } = new List<tbConfiguracionFacturas>();

    public virtual ICollection<tbConfiguracionFacturas> tbConfiguracionFacturasUsua_ModificacionNavigation { get; set; } = new List<tbConfiguracionFacturas>();

    public virtual ICollection<tbCuentasPorCobrar> tbCuentasPorCobrarUsua_CreacionNavigation { get; set; } = new List<tbCuentasPorCobrar>();

    public virtual ICollection<tbCuentasPorCobrar> tbCuentasPorCobrarUsua_ModificacionNavigation { get; set; } = new List<tbCuentasPorCobrar>();

    public virtual ICollection<tbDepartamentos> tbDepartamentosUsua_CreacionNavigation { get; set; } = new List<tbDepartamentos>();

    public virtual ICollection<tbDepartamentos> tbDepartamentosUsua_ModificacionNavigation { get; set; } = new List<tbDepartamentos>();

    public virtual ICollection<tbDescuentoPorClientes> tbDescuentoPorClientesUsua_CreacionNavigation { get; set; } = new List<tbDescuentoPorClientes>();

    public virtual ICollection<tbDescuentoPorClientes> tbDescuentoPorClientesUsua_ModificacionNavigation { get; set; } = new List<tbDescuentoPorClientes>();

    public virtual ICollection<tbDescuentosDetalle> tbDescuentosDetalleUsua_CreacionNavigation { get; set; } = new List<tbDescuentosDetalle>();

    public virtual ICollection<tbDescuentosDetalle> tbDescuentosDetalleUsua_ModificacionNavigation { get; set; } = new List<tbDescuentosDetalle>();

    public virtual ICollection<tbDescuentosPorEscala> tbDescuentosPorEscalaUsua_CreacionNavigation { get; set; } = new List<tbDescuentosPorEscala>();

    public virtual ICollection<tbDescuentosPorEscala> tbDescuentosPorEscalaUsua_ModificacionNavigation { get; set; } = new List<tbDescuentosPorEscala>();

    public virtual ICollection<tbDescuentos> tbDescuentosUsua_CreacionNavigation { get; set; } = new List<tbDescuentos>();

    public virtual ICollection<tbDescuentos> tbDescuentosUsua_ModificacionNavigation { get; set; } = new List<tbDescuentos>();

    public virtual ICollection<tbDevolucionesDetalle> tbDevolucionesDetalleUsua_CreacionNavigation { get; set; } = new List<tbDevolucionesDetalle>();

    public virtual ICollection<tbDevolucionesDetalle> tbDevolucionesDetalleUsua_ModificacionNavigation { get; set; } = new List<tbDevolucionesDetalle>();

    public virtual ICollection<tbDevoluciones> tbDevolucionesUsua_CreacionNavigation { get; set; } = new List<tbDevoluciones>();

    public virtual ICollection<tbDevoluciones> tbDevolucionesUsua_ModificacionNavigation { get; set; } = new List<tbDevoluciones>();

    public virtual ICollection<tbDireccionesPorCliente> tbDireccionesPorClienteUsua_CreacionNavigation { get; set; } = new List<tbDireccionesPorCliente>();

    public virtual ICollection<tbDireccionesPorCliente> tbDireccionesPorClienteUsua_ModificacionNavigation { get; set; } = new List<tbDireccionesPorCliente>();

    public virtual ICollection<tbEmpleados> tbEmpleadosUsua_CreacionNavigation { get; set; } = new List<tbEmpleados>();

    public virtual ICollection<tbEmpleados> tbEmpleadosUsua_ModificacionNavigation { get; set; } = new List<tbEmpleados>();

    public virtual ICollection<tbEstadosCiviles> tbEstadosCivilesUsua_CreacionNavigation { get; set; } = new List<tbEstadosCiviles>();

    public virtual ICollection<tbEstadosCiviles> tbEstadosCivilesUsua_ModificacionNavigation { get; set; } = new List<tbEstadosCiviles>();

    public virtual ICollection<tbFacturasDetalle> tbFacturasDetalleUsua_CreacionNavigation { get; set; } = new List<tbFacturasDetalle>();

    public virtual ICollection<tbFacturasDetalle> tbFacturasDetalleUsua_ModificacionNavigation { get; set; } = new List<tbFacturasDetalle>();

    public virtual ICollection<tbFacturas> tbFacturasUsua_CreacionNavigation { get; set; } = new List<tbFacturas>();

    public virtual ICollection<tbFacturas> tbFacturasUsua_ModificacionNavigation { get; set; } = new List<tbFacturas>();

    public virtual ICollection<tbImpuestos> tbImpuestosUsua_CreacionNavigation { get; set; } = new List<tbImpuestos>();

    public virtual ICollection<tbImpuestos> tbImpuestosUsua_ModificacionNavigation { get; set; } = new List<tbImpuestos>();

    public virtual ICollection<tbInventarioBodegas> tbInventarioBodegasUsua_CreacionNavigation { get; set; } = new List<tbInventarioBodegas>();

    public virtual ICollection<tbInventarioBodegas> tbInventarioBodegasUsua_ModificacionNavigation { get; set; } = new List<tbInventarioBodegas>();

    public virtual ICollection<tbInventarioSucursales> tbInventarioSucursalesUsua_CreacionNavigation { get; set; } = new List<tbInventarioSucursales>();

    public virtual ICollection<tbInventarioSucursales> tbInventarioSucursalesUsua_ModificacionNavigation { get; set; } = new List<tbInventarioSucursales>();

    public virtual ICollection<tbMarcas> tbMarcasUsua_CreacionNavigation { get; set; } = new List<tbMarcas>();

    public virtual ICollection<tbMarcas> tbMarcasUsua_ModificacionNavigation { get; set; } = new List<tbMarcas>();

    public virtual ICollection<tbMarcasVehiculos> tbMarcasVehiculosUsua_CreacionNavigation { get; set; } = new List<tbMarcasVehiculos>();

    public virtual ICollection<tbMarcasVehiculos> tbMarcasVehiculosUsua_ModificacionNavigation { get; set; } = new List<tbMarcasVehiculos>();

    public virtual ICollection<tbModelos> tbModelosUsua_CreacionNavigation { get; set; } = new List<tbModelos>();

    public virtual ICollection<tbModelos> tbModelosUsua_ModificacionNavigation { get; set; } = new List<tbModelos>();

    public virtual ICollection<tbMunicipios> tbMunicipiosUsua_CreacionNavigation { get; set; } = new List<tbMunicipios>();

    public virtual ICollection<tbMunicipios> tbMunicipiosUsua_ModificacionNavigation { get; set; } = new List<tbMunicipios>();

    public virtual ICollection<tbPedidosDetalle> tbPedidosDetalleUsua_CreacionNavigation { get; set; } = new List<tbPedidosDetalle>();

    public virtual ICollection<tbPedidosDetalle> tbPedidosDetalleUsua_ModificacionNavigation { get; set; } = new List<tbPedidosDetalle>();

    public virtual ICollection<tbPedidos> tbPedidosUsua_CreacionNavigation { get; set; } = new List<tbPedidos>();

    public virtual ICollection<tbPedidos> tbPedidosUsua_ModificacionNavigation { get; set; } = new List<tbPedidos>();

    public virtual ICollection<tbPermisos> tbPermisosUsua_CreacionNavigation { get; set; } = new List<tbPermisos>();

    public virtual ICollection<tbPermisos> tbPermisosUsua_ModificacionNavigation { get; set; } = new List<tbPermisos>();

    public virtual ICollection<tbPreciosPorProducto> tbPreciosPorProductoUsua_CreacionNavigation { get; set; } = new List<tbPreciosPorProducto>();

    public virtual ICollection<tbPreciosPorProducto> tbPreciosPorProductoUsua_ModificacionNavigation { get; set; } = new List<tbPreciosPorProducto>();

    public virtual ICollection<tbProductos> tbProductosUsua_CreacionNavigation { get; set; } = new List<tbProductos>();

    public virtual ICollection<tbProductos> tbProductosUsua_ModificacionNavigation { get; set; } = new List<tbProductos>();

    public virtual ICollection<tbPromocionesDetalle> tbPromocionesDetalleUsua_CreacionNavigation { get; set; } = new List<tbPromocionesDetalle>();

    public virtual ICollection<tbPromocionesDetalle> tbPromocionesDetalleUsua_ModificacionNavigation { get; set; } = new List<tbPromocionesDetalle>();

    public virtual ICollection<tbPromociones> tbPromocionesUsua_CreacionNavigation { get; set; } = new List<tbPromociones>();

    public virtual ICollection<tbPromociones> tbPromocionesUsua_ModificacionNavigation { get; set; } = new List<tbPromociones>();

    public virtual ICollection<tbProveedores> tbProveedoresUsua_CreacionNavigation { get; set; } = new List<tbProveedores>();

    public virtual ICollection<tbProveedores> tbProveedoresUsua_ModificacionNavigation { get; set; } = new List<tbProveedores>();

    public virtual ICollection<tbPuntosEmision> tbPuntosEmisionUsua_CreacionNavigation { get; set; } = new List<tbPuntosEmision>();

    public virtual ICollection<tbPuntosEmision> tbPuntosEmisionUsua_ModificacionNavigation { get; set; } = new List<tbPuntosEmision>();

    public virtual ICollection<tbRecargasDetalle> tbRecargasDetalleUsua_CreacionNavigation { get; set; } = new List<tbRecargasDetalle>();

    public virtual ICollection<tbRecargasDetalle> tbRecargasDetalleUsua_ModificacionNavigation { get; set; } = new List<tbRecargasDetalle>();

    public virtual ICollection<tbRecargas> tbRecargasUsua_ConfirmacionNavigation { get; set; } = new List<tbRecargas>();

    public virtual ICollection<tbRecargas> tbRecargasUsua_CreacionNavigation { get; set; } = new List<tbRecargas>();

    public virtual ICollection<tbRecargas> tbRecargasUsua_ModificacionNavigation { get; set; } = new List<tbRecargas>();

    public virtual ICollection<tbRegistrosCAI> tbRegistrosCAIUsua_CreacionNavigation { get; set; } = new List<tbRegistrosCAI>();

    public virtual ICollection<tbRegistrosCAI> tbRegistrosCAIUsua_ModificacionNavigation { get; set; } = new List<tbRegistrosCAI>();

    public virtual ICollection<tbRoles> tbRolesUsua_CreacionNavigation { get; set; } = new List<tbRoles>();

    public virtual ICollection<tbRoles> tbRolesUsua_ModificacionNavigation { get; set; } = new List<tbRoles>();

    public virtual ICollection<tbRutas> tbRutasUsua_CreacionNavigation { get; set; } = new List<tbRutas>();

    public virtual ICollection<tbRutas> tbRutasUsua_ModificacionNavigation { get; set; } = new List<tbRutas>();

    public virtual ICollection<tbSubcategorias> tbSubcategoriasUsua_CreacionNavigation { get; set; } = new List<tbSubcategorias>();

    public virtual ICollection<tbSubcategorias> tbSubcategoriasUsua_ModificacionNavigation { get; set; } = new List<tbSubcategorias>();

    public virtual ICollection<tbSucursales> tbSucursalesUsua_CreacionNavigation { get; set; } = new List<tbSucursales>();

    public virtual ICollection<tbSucursales> tbSucursalesUsua_ModificacionNavigation { get; set; } = new List<tbSucursales>();

    public virtual ICollection<tbTrasladosDetalle> tbTrasladosDetalleUsua_CreacionNavigation { get; set; } = new List<tbTrasladosDetalle>();

    public virtual ICollection<tbTrasladosDetalle> tbTrasladosDetalleUsua_ModificacionNavigation { get; set; } = new List<tbTrasladosDetalle>();

    public virtual ICollection<tbTraslados> tbTrasladosUsua_CreacionNavigation { get; set; } = new List<tbTraslados>();

    public virtual ICollection<tbTraslados> tbTrasladosUsua_ModificacionNavigation { get; set; } = new List<tbTraslados>();

    public virtual ICollection<tbVendedoresPorRuta> tbVendedoresPorRutaUsua_CreacionNavigation { get; set; } = new List<tbVendedoresPorRuta>();

    public virtual ICollection<tbVendedoresPorRuta> tbVendedoresPorRutaUsua_ModificacionNavigation { get; set; } = new List<tbVendedoresPorRuta>();

    public virtual ICollection<tbVendedores> tbVendedoresUsua_CreacionNavigation { get; set; } = new List<tbVendedores>();

    public virtual ICollection<tbVendedores> tbVendedoresUsua_ModificacionNavigation { get; set; } = new List<tbVendedores>();
}