// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIDCOP_Backend.Entities.Entities;

public partial class tbVendedores
{
    public int Vend_Id { get; set; }

    public string Vend_Codigo { get; set; }

    public string Vend_DNI { get; set; }

    public string Vend_Nombres { get; set; }

    public string Vend_Apellidos { get; set; }

    public string Vend_Telefono { get; set; }

    public string Vend_Correo { get; set; }

    public string Vend_Sexo { get; set; }

    public string Vend_DireccionExacta { get; set; }

    public int Sucu_Id { get; set; }

    public int Colo_Id { get; set; }

    public int? Vend_Supervisor { get; set; }

    public int? Vend_Ayudante { get; set; }

    public string Vend_Tipo { get; set; }

    public bool? Vend_EsExterno { get; set; }

    public bool Vend_Estado { get; set; }

    public int Usua_Creacion { get; set; }

    public DateTime Vend_FechaCreacion { get; set; }

    public int? Usua_Modificacion { get; set; }

    public DateTime? Vend_FechaModificacion { get; set; }

    public string Vend_Imagen { get; set; }

    public virtual tbColonias Colo { get; set; }

    public virtual tbSucursales Sucu { get; set; }

    public virtual tbUsuarios Usua_CreacionNavigation { get; set; }

    public virtual tbUsuarios Usua_ModificacionNavigation { get; set; }

    public virtual tbEmpleados Vend_AyudanteNavigation { get; set; }

    public virtual tbEmpleados Vend_SupervisorNavigation { get; set; }

    public virtual ICollection<tbBodegas> tbBodegas { get; set; } = new List<tbBodegas>();

    public virtual ICollection<tbFacturas> tbFacturas { get; set; } = new List<tbFacturas>();

    public virtual ICollection<tbPedidos> tbPedidos { get; set; } = new List<tbPedidos>();

    public virtual ICollection<tbVendedoresPorRuta> tbVendedoresPorRuta { get; set; } = new List<tbVendedoresPorRuta>();
}