// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIDCOP_Backend.Entities.Entities;

public partial class tbVendedoresPorRuta
{
    public int VeRu_Id { get; set; }

    public int Vend_Id { get; set; }

    public int Ruta_Id { get; set; }

    public string VeRu_Dia { get; set; }

    public bool Vend_Estado { get; set; }

    public int Usua_Creacion { get; set; }

    public DateTime Vend_FechaCreacion { get; set; }

    public int? Usua_Modificacion { get; set; }

    public DateTime? Vend_FechaModificacion { get; set; }

    public virtual tbRutas Ruta { get; set; }

    public virtual tbUsuarios Usua_CreacionNavigation { get; set; }

    public virtual tbUsuarios Usua_ModificacionNavigation { get; set; }

    public virtual tbVendedores Vend { get; set; }
}